name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: |
            packages/server/package-lock.json
            packages/client/package-lock.json
      - 
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Ho_Chi_Minh"

      - name: Create env file
        working-directory: packages/server
        run: |
          touch .env.test
          echo NODE_ENV=test >> .env.test
          
          echo JWT_SECRET=test >> .env.test
          echo JWT_EXPIRATION='10m' >> .env.test

          echo POSTGRES_HOST=localhost >> .env.test
          echo POSTGRES_PORT=5432 >> .env.test
          echo POSTGRES_USER=test_user >> .env.test
          echo POSTGRES_PASSWORD=test_pw >> .env.test
          echo POSTGRES_DB=test_db >> .env.test
          echo DATABASE_URL=postgres://test_user:test_pw@localhost:5432/test_db >> .env.test

      - name: Install server dependencies
        run: |
          cd packages/server
          npm ci

      - name: Install client dependencies
        run: |
          cd packages/client
          npm ci

      - name: Lint server
        run: |
          cd packages/server
          npm run lint

      # - name: Lint client
      #   run: |
      #     cd packages/client
      #     npm run lint

      # - name: Build client
      #   run: |
      #     cd packages/client
      #     npm run build

      - name: Test server
        run: |
          cd packages/server
          npm run test